# The api key, secret key, and canvas page name are required to get started
# Tunnel configuration is only needed if you are going to use the facebooker:tunnel Rake tasks
# Your callback url in Facebook should be set to http://public_host:public_port
# If you're building a Facebook connect site, 
#    change the value of set_asset_host_to_callback_url to false
# To develop for the new profile design, add the following key..
# api: new
# remove the key or set it to anything else to use the old facebook design.
# This should only be necessary until the final version of the new profile is released.

development:
  api_key: 9d3e1a276ec3dba79b280600fe2b73e2
  secret_key: 294ac76c01ab79366d35151d397df03c
  canvas_page_name: apigeesandbox
  callback_url: http://elbowdrum.com/sandbox
  pretty_errors: true
  set_asset_host_to_callback_url: true
  tunnel:
    public_host_username: 
    public_host: 
    public_port: 4007
    local_port: 3000
    server_alive_interval: 0

test:
  api_key: 7335f7df8964439d94a1be6821661126
  secret_key: 634c95ab3d8eeaaf8063c506fdce8462
  canvas_page_name: open_stream_growl
  callback_url: http://elbowdrum.com
  pretty_errors: true
  set_asset_host_to_callback_url: true
  tunnel:
    public_host_username: 
    public_host: 
    public_port: 4007
    local_port: 3000
    server_alive_interval: 0

production:
  api_key: 7335f7df8964439d94a1be6821661126
  secret_key: 634c95ab3d8eeaaf8063c506fdce8462
  canvas_page_name: open_stream_growl
  callback_url: http://elbowdrum.com
  pretty_errors: true
  set_asset_host_to_callback_url: true
  tunnel:
    public_host_username: 
    public_host: 
    public_port: 4007
    local_port: 3000
    server_alive_interval: 0
